[profile.default]
src = "contract/src"
test = "contract/test"
out = "out"
libs = ["contract/lib"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
